// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtYHNLMQ3XRPMZm6U6RF42wm_D-QY8ShI',
    appId: '1:494136345323:web:1d90151506e5f9b36bb4ae',
    messagingSenderId: '494136345323',
    projectId: 'mindtrack-3e623',
    authDomain: 'mindtrack-3e623.firebaseapp.com',
    storageBucket: 'mindtrack-3e623.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6yS3fuTj1mWi-lgCx4232zIBmITzPGKs',
    appId: '1:494136345323:android:f3ce1a794c8dc0fa6bb4ae',
    messagingSenderId: '494136345323',
    projectId: 'mindtrack-3e623',
    storageBucket: 'mindtrack-3e623.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY4x5aSAARtFzQ7DFiHJQgPdhK3hLJ8n0',
    appId: '1:494136345323:ios:0d74f52ff218e8666bb4ae',
    messagingSenderId: '494136345323',
    projectId: 'mindtrack-3e623',
    storageBucket: 'mindtrack-3e623.firebasestorage.app',
    iosBundleId: 'com.example.mindtrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY4x5aSAARtFzQ7DFiHJQgPdhK3hLJ8n0',
    appId: '1:494136345323:ios:0d74f52ff218e8666bb4ae',
    messagingSenderId: '494136345323',
    projectId: 'mindtrack-3e623',
    storageBucket: 'mindtrack-3e623.firebasestorage.app',
    iosBundleId: 'com.example.mindtrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtYHNLMQ3XRPMZm6U6RF42wm_D-QY8ShI',
    appId: '1:494136345323:web:1c134ec4c67be37f6bb4ae',
    messagingSenderId: '494136345323',
    projectId: 'mindtrack-3e623',
    authDomain: 'mindtrack-3e623.firebaseapp.com',
    storageBucket: 'mindtrack-3e623.firebasestorage.app',
  );
}
